sudo: false
language: node_js
node_js:
- '8'
cache:
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_14d8bac34dff_key -iv $encrypted_14d8bac34dff_iv -in creds.tar.enc -out creds.tar -d
- tar xvf creds.tar
- cp -rf d2lcredentials/ src/
install:
- npm install
script:
- npm run test
after_success:
- npm run codecov
