sudo: false
language: node_js
node_js:
  - "8"

cache:
  directories:
    - node_modules

before_install:
  - openssl aes-256-cbc -K $encrypted_14d8bac34dff_key -iv $encrypted_14d8bac34dff_iv -in _dev.credentials.js.enc -out d2lcredentials/_dev.credentials.js -d
  - openssl aes-256-cbc -K $encrypted_14d8bac34dff_key -iv $encrypted_14d8bac34dff_iv -in index.js.enc -out d2lcredentials/index.js -d

install:
  - npm install

script:
  - npm run test

after_success:
  - npm run codecov
